### PR TITLE
Update S70 bulk data

### PR DESCRIPTION
**Pull request by jseppi**
New Schedule 70 bulk data. This PR just updates the bulk csv files.

### CODE REVIEW

**Comment by jseppi** [comment]
[Load new IT S70 data into production](https://trello.com/c/4yMdVU1H/240-load-new-it-s70-data-into-production)

**Comment by jseppi** [comment]
Data have been loaded into production.

**Comment by jseppi** [comment]
awaiting https://github.com/18F/calc/pull/1419 hopefull

**Comment by jseppi** [comment]
Think this is "safe" to merge, @toolness?

**Comment by toolness** [comment]
Yeah let's do it!

**Pull request merged**
