### PR TITLE
Tag and release v2.0.0

### PR DESCRIPTION
**Pull request by toolness**
### Added

- The new data capture functionality has been added, allowing COs
  to log in (via cloud.gov) and submit their approved Schedule 70
  price lists. Data administrators can then review these price lists and
  add their data into CALC.

- Additionally, data administrators can directly upload Region 10
  bulk data. The uploaded data will then replace all existing Region 10
  data in CALC.

### Changed

- In October 2015, the schedules represented in CALC were consolidated
  into the [Professional Services Schedule][pss] to give federal agency
  acquisition professionals the ability to obtain total contract solutions
  for their professional services requirements using one contract vehicle.

  Consequently, the "Schedule" filter in the data explorer has
  been renamed to the "SIN / Schedule" filter, and allows rates to be
  filtered by SIN number.

- Searching for multiple words in the data explorer's search field
  now produces expected autocompletion results.

- The data explorer is now much more keyboard-accessible and
  screenreader-friendly.

- The "proposed price" field in the data explorer automatically
  updates the histogram on a per-keypress basis; there is no longer
  any need to click the "Go" button.

- Sharing CALC links with the "Education" field filled out now works
  properly.

- The CALC banner has been redesigned to be less confusing and easier
  to read.

- Google Analytics for CALC now properly track new searches in the
  data explorer as page views. We also track clicks on links in the
  "Contract #" column of the data explorer results table.

[pss]: https://www.gsa.gov/portal/content/246403

### CODE REVIEW

**Comment by toolness** [comment]
Oof. Is there an easy way to say "resolve all merge conflicts by favouring the v2.0.0-rc branch"?

**Comment by toolness** [comment]
Ooo I found http://gitready.com/advanced/2009/02/25/keep-either-file-in-merge-conflicts.html

**Comment by toolness** [comment]
This feels a wee bit odd because of the fact that `master` has its own hotfix changes applied since we forked `develop` back in June or whenever.  I *think* I resolved all the conflicts OK but we shall see.

**Comment by toolness** [comment]
Hooray!  Does "wooooo!" satisfy "Wait for the stakeholders to sign-off on the release" as mentioned in step 5 of [`RELEASE.md`](https://github.com/18F/calc/blob/develop/RELEASE.md)?

**Comment by jseppi** [comment]
I think, for this release, yes since our product owner has already signed off on the functionality included in this release.

**Comment by toolness** [comment]
Ok, I just merged this, so it should show up at https://calc-staging.app.cloud.gov soon!

**Comment by jseppi** [comment]
🤞

**Comment by jseppi** [comment]
Nice, deployment worked!

**Pull request merged**
