### PR TITLE
Upgrade python and node deps (other than django and djorm-ext-pgfulltext)

### PR DESCRIPTION
**Pull request by jseppi**
Upgrading dependencies for ATO

I've upgrade all python and node dependencies per [Gemnasium](https://gemnasium.com/github.com/18F/calc), except for Django and djorm-ext-pgfulltext (see #540 for reasons).

Closes https://github.com/18F/calc/issues/540

### CODE REVIEW

**Comment by jseppi** [comment]
Tests are passing locally, investigating travis failures...

**Comment by jseppi** [comment]
The tests pass locally, so I'm not sure what the deal is.
Travis is reporting that they are having some issues today: https://www.traviscistatus.com/incidents/11hp8bhkrkn7 Hoping this will clear itself up...

**Comment by jseppi** [comment]
Hrm, actually my _local_ tests are indeed wrong because I had some stale packages installed in my local virtualenv.

**Comment by jseppi** [comment]
The failing management command is `update_search_field`, which is part of [djorm-ext-pgfulltext](https://github.com/linuxlewis/djorm-ext-pgfulltext). Since we are being asked to also upgrade Django (and I haven't done that yet in this PR), perhaps this is a good time to try the 1.10 Django and use its native text search, and remove djorm-ext-pgfulltext.

related: https://github.com/18F/calc/issues/516 and #291

**Comment by jseppi** [comment]
Ready for review, @toolness

**Comment by toolness** [comment]
Yeah wooot!

**Pull request merged**
