### PR TITLE
A few copy edits

### PR DESCRIPTION
**Pull request by kategarklavs**
Just added a salutation & closing. Also, one question — how quickly will a CALC team member respond to a customer question? (I ask because it might be nice to add this information to the last paragraph: "If you have any questions, just reply to this email — we'll get back to you within one business day."

### CODE REVIEW

**Comment by jseppi** [comment]
Good question. @tram: What do you think? Do we want to have even a soft-guarantee of question turn-around time?

**Comment by kategarklavs** [comment]
@jseppi If not, that's also OK — if there is a guarantee, though, I always like to include it!

**Comment by jseppi** [comment]
Would something like "We'll try to get back to you within one or two business days." work?

**Comment by kategarklavs** [comment]
Howdy! Yep, I think that works — I might shorten it "We'll get back to you
within two business days" (only because then, if you all respond more
quickly, folks will be extra pleased at the "quick" response —
underpromise/over deliver).

**Pull request closed without merging**
