### PR TITLE
Changes to Schedule filter

### LINKED ISSUE #1156: Change the Schedule filter title to: SIN / Schedule

### LINKED ISSUE #1157: Change the schedule filter to be descending
For example, it would go 899 down to 132 then have consolidated at the bottom.

### PR DESCRIPTION
**Pull request by jseppi**
- Change "Schedule" label to "SIN / Schedule". Closes #1156.
- Change order of "SIN / Schedule" dropdown options. Closes #1157.

Screenshot:

screen shot 2016-12-23 at 2 19 57 pm

### CODE REVIEW

**Comment by jseppi** [comment]
Logged #1158 about with size of filter labels.

**Comment by tram** [comment]
If they're descending, should SIN 87405 come before or after SIN 899?

**Comment by jseppi** [comment]
In #1157, @KellyBailey specifically mentioned having `899` be the first one.

**Comment by jseppi** [comment]
Sorted alphabetically according to number :P

**Comment by tram** [comment]
Right on. Looks good to me!

**Pull request merged**
