### PR TITLE
[Experiment] React-based tokenized autocomplete for main search input

### PR DESCRIPTION
**Pull request by jseppi**
Here's the new search box, but expanded to the full width of the page content area:
screen shot 2017-03-01 at 4 26 29 pm

Here's how it would look if the width is constrained and there are more tokens present than will fit within that width:
screen shot 2017-03-01 at 4 35 17 pm

Obviously something needs to happen with the radios and with the "Search" and "Clear" buttons in either case. I think the "Clear" button should be disassociated from the labor category search input because it actually clears everything (including all filters), not just that search input.

To Do:
- [ ] visual design
- [ ] allow free-form text token entry

### CODE REVIEW

**Comment by jseppi** [comment]
@ericronne what kind of design adjustments do you think would work for this change?

**Comment by ericronne** [comment]
Think it's testable in its current form?

**Comment by jseppi** [comment]
Yeah, you could get a sense of it in its current form

**Comment by ericronne** [comment]
@tram would you recommend that we do some testing on this before continuing with design? My gut is that the "tag" motif is intuitive and perhaps familiar to our users (CO's use pinterest, right? :) ), but i'd be curious to see how folks interact with it in this context.

cc @kellybailey

**Comment by jseppi** [comment]
I bet it is more intuitive than the comma-delimited thing we have going on now!

**Comment by jseppi** [comment]
I've been working also on a fix for #960 in here, but I think I am going to extract it and finish it up in a separate PR that will work on the existing Data Explorer.

**Comment by jseppi** [comment]
also maybe check out https://github.com/i-like-robots/react-tags or https://github.com/olahol/react-tagsinput

**Comment by jseppi** [comment]
[As a user I should not have confusion with labor category search tokens due to commas](https://trello.com/c/GUESfUPN/243-as-a-user-i-should-not-have-confusion-with-labor-category-search-tokens-due-to-commas)

**Comment by jseppi** [comment]
[As a user I should be able to search for a labor category with a comma in it (ex: Engineer, Junior)](https://trello.com/c/ncCHRIFd/245-as-a-user-i-should-be-able-to-search-for-a-labor-category-with-a-comma-in-it-ex-engineer-junior)

**Comment by ericronne** [comment]
@tram would you consider this design good enough for you to put in front of folks in nyc? @hbillings and i did some style adjustments. Not perfect, but i'm hesitant to spend too much styling before testing in some fashion...

haps8wuyx1

**Comment by hbillings** [comment]
I want to note here that it seems like with this library, you can only select something from the autocomplete list (if you don't select and you just hit enter, for instance, you'll automatically get the first thing in the list). This could be really confusing for folks who don't realize they've selected something other than what they entered (I typed in "engineer," hit enter, and the search term it populated was "senior engineer"). Just wanted to surface that somewhere!

**Comment by jseppi** [comment]
Good catch, @hbillings. I would suspect there's a setting for allowing free-form text tokens instead of only auto-completed tokens.

**Comment by toolness** [comment]
@jseppi i took an alternate approach in #1717... someone mentioned during coworking that only allowing users to enter items from the suggestion list could be considered a feature rather than a bug, since it doesn't make sense to search for something that there are no autocomplete results for.  so in #1717 i made the API results work in a way that supported that approach.

That said, now that I think about it, since we're showing the _normalized_ labor category in the autocomplete list, there may be cases where someone looking for an _exact match_ might not find their labor category in the autocomplete list.  Eh, anyways, we can talk about it later.

**Comment by toolness** [comment]
I haven't tried this PR out on a screen reader, but for what it's worth, gov.uk just published a blog post called [What we learned from getting our autocomplete tested for accessibility](https://accessibility.blog.gov.uk/2018/05/15/what-we-learned-from-getting-our-autocomplete-tested-for-accessibility/).

**Comment by ericronne** [comment]
Insufficient evidence that users would benefit :)

**Pull request closed without merging**
