### PR TITLE
Cache pip in travis

### LINKED ISSUE #1042: Enable Travis cache
I just learned that you can enable caching in Travis for either arbitrary directories, or for pre-configured package management systems, like [`pip`](https://docs.travis-ci.com/user/caching/#pip-cache).

It might help our builds go a little faster.

### PR DESCRIPTION
**Pull request by jseppi**
Closes #1042 

To Do:
- [x] verify it works

### CODE REVIEW

**Comment by jseppi** [comment]
Dangit, looks like it didn't work:

screen shot 2016-11-17 at 10 39 18 am

**Comment by jseppi** [comment]
Woot! I restarted this PR's build, and the cache did appear to work! It probably just didn't work the first time because there was nothing cached (duh).

screen shot 2016-11-17 at 10 48 56 am

**Comment by jseppi** [comment]
Good to go, @toolness?

**Comment by jseppi** [comment]
Builds look somewhat faster. Our successful builds are ~3 mins 30 secs. After adding `pip` anode `node_modules` caching, this build took under 3 minutes.

screen shot 2016-11-17 at 11 12 46 am

**Comment by jseppi** [comment]
SAAAAAAAAAAAAAAAAAAUUUUUUUUUUCE

image

**Comment by toolness** [comment]
this is ULTRA cool 👍 

Thanks!!!!

**Pull request merged**
