### PR TITLE
Validate contract_number, spruce up some tests

### PR DESCRIPTION
**Pull request by jseppi**
This PR adds some minor regex-based validation to the contract_number field so that it can only contain alphanumeric and dash characters.

screen shot 2016-12-07 at 9 11 34 am

### CODE REVIEW

**Comment by jseppi** [comment]
Ready for review @toolness.

Any reason _not_ to do this, @tram?

**Comment by tram** [comment]
Looks good to me! Will we be able to capture when people are shown formatting errors? It would be helpful to see where folks are running into roadblocks.

**Comment by jseppi** [comment]
We potentially could. I think it would involve some javascript that runs on page load and looks for validation error elements or text and fires a GA event if found.

**Comment by toolness** [comment]
As long as actual real-world contract numbers actually obey the constraints we're adding here, I think this is good to merge!

**Comment by jseppi** [comment]
Confirmed by Kelly!

**Pull request merged**
