### PR TITLE
Fix admin data table wonkiness

### LINKED ISSUE #1970: Fix wonkiness on data admin tables
The arrows show up in the wrong place, the Django sort order indicator is _weird_, and the currency symbol is in the wrong place.
screen shot 2018-05-29 at 2 55 06 pm

### PR DESCRIPTION
**Pull request by hbillings**
Closes #1970. Looks like this now:

screen shot 2018-05-29 at 3 43 03 pm

### CODE REVIEW

**Comment by hbillings** [comment]
I _think_ both those two things are how it currently looks on prod. (The arrow only shows up if you sort, for some bizarre reason.) SecureAuth is hanging on me, so I can't get in to check right now. 😭

**Comment by ericronne** [comment]
And i can't check because i'm a plebian prod-wise, sigh

**Comment by hbillings** [comment]
@ericronne actually, turns out I am too. sigh. Gonna have to wait for @toolness to get back!

**Comment by ericronne** [comment]
Looks like this PR has been super-sighs-ed. :P

**Comment by hbillings** [comment]
Okay, I'm going to merge this and open new issues for those two things, since there are only two data admins right now, and one of them doesn't use sort.

**Pull request merged**
