### PR TITLE
add crlf rule for .csv files

### LINKED ISSUE #1414: Fresh git clones show modified CSV and/or JS files
This is really weird and I can't tell if it's something strange on my system, or something strange with our repo.

Basically, when I do a fresh checkout of our repo, via `git clone https://github.com/18F/calc`, `cd` into it and run `git status`, I get this:

> screen shot 2017-02-21 at 5 20 31 pm

Wut.

This might have something bizarre to do with our `.gitattributes` but I'm not sure; doing a `git diff` on the files shows all the lines removed but then added with no apparent differences, which could mean that the line endings just changed.

@jseppi can you reproduce this on your end? If not, it's probably something wonky with my system.

### PR DESCRIPTION
**Pull request by jseppi**
Closes #1414 

I hope

### CODE REVIEW

**Comment by jseppi** [comment]
Does this appear to work for you @toolness?

**Comment by toolness** [comment]
@jseppi is #1414 even a problem anymore?  While I haven't made a fresh git clone in a while, I haven't noticed weird issues with line endings on CSV or JS files either... Previously I was experiencing lots of weirdness as I switched branches and stuff.

**Comment by jseppi** [comment]
I haven't had a problem either, but maybe merging #1408 will make the problems come back? I'm not sure why the problem disappeared...

**Comment by jseppi** [comment]
Closing because this doesn't work

**Pull request closed without merging**
