### PR TITLE
Enforce case-insensitive user email addresses

### LINKED ISSUE #1040: UaaBackend lookup for user email should be case-insensitive
Looks like the cloud.gov SecureAuth broker always returns the user email address in lowercase. So if we create a user in the Django admin with any capitalization, that user will not actually be able to login.

### PR DESCRIPTION
**Pull request by jseppi**
Closes #1040 

Email uniqueness is not enforced is if a user is created via `manage.py`, but this was already the case.

### CODE REVIEW

**Comment by jseppi** [comment]
ready for review @toolness

**Comment by jseppi** [comment]
SAUUUUCCCCEEEEEE FFFFFUUUUUUUUU

**Comment by jseppi** [comment]
ugh, failed sauce even after a build restart

local results:

```sh
jamesseppi at XCOH2J-0TMFVH8 in ~/CODE/CALC (case-insensitive-auth-email)
$ docker-compose run app python manage.py ultratest
Connection to database established.
  _    _ _ _          _______        _
 | |  | | | |        |__   __|      | |
 | |  | | | |_ _ __ __ _| | ___  ___| |_
 | |  | | | __| '__/ _` | |/ _ \/ __| __|
 | |__| | | |_| | | (_| | |  __/\__ \ |_
  \____/|_|\__|_|  \__,_|_|\___||___/\__|

Running ALL THE TESTS
-> flake8 OK
-> eslint OK
-> bandit OK
-> py.test OK
Coverage: 87.50% (same as last run)
```

**Comment by toolness** [comment]
Yassss 👍  :shipit: 

SAUUUUCCCCEEEEEE FFFFFUUUUUUUUU 😣

**Comment by jseppi** [comment]
mornings seem to be better for sauce

**Pull request merged**
