### PR TITLE
Styleguide accessibility updates

### PR DESCRIPTION
**Pull request by ericronne**
Adds a small introductory section on accessibility, along with some accessibility-related updates to the color section. 

… and v minor stylingz ;)

### CODE REVIEW

**Comment by toolness** [comment]
Nice, I like the copy changes!

**Comment by ericronne** [comment]
@toolness / @hbillings if you want to add some notes about coding for accessibility, feel free. Not critical to have, though, since i've linked to the accessibility guide in the text.

@hbillings i need a hand with specificity at some point, if you get a sec! thx

**Comment by ericronne** [comment]
Closes #1896 **and** #1897

**Comment by ericronne** [comment]
<bump>Bump!</bump>

**Pull request merged**
