### PR TITLE
Fix accessibility regressions

### LINKED ISSUE #1975: Keyboard accessibility regressions on data explorer
I was using <kbd>Tab</kbd> to navigate the Data Explorer on the latest `develop` and noticed a few regressions from our current `master` (i.e., what's at calc.gsa.gov):

1. The "education level" drop-down no longer has a focus indicator. On `master` there's a fuzzy blue outline, but on `develop` there's no indication.

2. The "experience" slider's knobs are focusable, but pressing a variety of keys (enter, space, arrow keys, etc) doesn't do anything. On `master` these aren't focusable, as the `<select>` widgets below the knobs control the same values (these widgets are also still focusable on `develop`).  If there's nothing interactive that can be done with these knobs, we should probably remove them from the tab order like they are on `master`.

3. The "contract year" radios no longer have any focus indication. On `master` there's a fuzzy blue outline around whatever the currently-selected radio button is.

### PR DESCRIPTION
**Pull request by hbillings**
Closes #1975.

- Fixes focus ring on tab around Education button.
- Adds back focus on contract year. Note that this is funky because the markup here is _super_ odd.
On click it looks like:
screen shot 2018-05-30 at 1 54 06 pm
But on tab it looks like:
screen shot 2018-05-30 at 1 53 52 pm
This is because it's actually two different elements getting focus at different points, and I don't know how to reconcile the styles. >_<

To do:
- [x] Fix focus ring color around radio buttons
- [x] Fix focus ring color on education level checkboxes

Not doing:
- Fixing the tab focus on the slider handles. Because this is a component we're rendering from a library, we don't have much control over it, and nothing I've tried (mostly around `tabindex`) manages to take it out of the tab flow.

### CODE REVIEW

**Comment by ericronne** [comment]
I also see that focus state on the three search-term radio buttons is too light in color, and you can't tab between the three options. It only tabs to the selected one.

image

It looks like the intent was for the term and its associated radio button to get the focus, like so:

image

This makes sense, since clicking on the term itself serves to select that option:

m5nxppwizn

**Comment by hbillings** [comment]
Can you pull again, @ericronne? I fixed the color.

**Comment by hbillings** [comment]
Oh, also, these are weird: The focus state you're seeing that selects everything is really due to us having a generic `:focus` class that applies to _anything_. We really only want it to apply to the input (or, in this case, the thing that appears to be the input).

**Comment by ericronne** [comment]
Color around the dot is now correct, but is it tab-key accessible?

**Comment by hbillings** [comment]
It is for me; is it not for you?

**Comment by ericronne** [comment]
Could be my messed-up local environment, but here's what tabbing does for me …

c1nhdwuj7p

**Comment by hbillings** [comment]
Oh, so this is an odd thing with radio buttons: tabbing selects the _group_ of them. Once you're in the group, you use the arrow keys to select the one you want. I don't know why that's how it works?

**Comment by ericronne** [comment]
Education filter is also buggy (see #1982). Not a new problem. NBD if we can't fix this today.

**Pull request merged**
