### PR TITLE
add R10 upload link to admin; change admin header title

### LINKED ISSUE #591: R10 Upload - Add link to upload flow when logged in user is_staff
There is currently not a link anywhere to the R10 bulk upload flow, so the user has to know the URL. A link should be added somewhere, probably to the logged-in user header box.

### PR DESCRIPTION
**Pull request by jseppi**
Changes Admin header to this:

screen shot 2016-08-26 at 11 02 31 am

Closes #591

### CODE REVIEW

**Comment by jseppi** [comment]
ready for review @toolness

**Comment by toolness** [comment]
Woooooo thanks!

**Comment by toolness** [comment]
Feel free to merge once travis is happy.

**Comment by jseppi** [comment]
hrm, actually maybe I should change that `Welcome, <username>` to `Welcome, <email address>` here as well.

**Comment by toolness** [comment]
O a fair point.  Up to you!

**Pull request merged**
