### PR TITLE
Ignore unresolved imports from eslint for Docker support.

### PR DESCRIPTION
**Pull request by toolness**
This is a workaround for https://github.com/benmosher/eslint-plugin-import/issues/142. I figure it's OK to ignore this warning since there's a very high likelihood that our code simply won't run / compile if there are any unresolved imports.

### CODE REVIEW

**Comment by toolness** [comment]
Thoughts on this @jseppi ?  It's an annoying trade-off, for sure... another possibility might be to have ultratest check to see if its running in docker and supply the ignore information [via command-line](http://eslint.org/docs/user-guide/command-line-interface#rule) if so, so that non-docker tests don't suffer because of this.

**Comment by jseppi** [comment]
I think I'd prefer it via command-line in `ULTRATEST` because I've actually had this rule be helpful when run eslint is running via in my editor's eslint plugin.

**Comment by toolness** [comment]
Cool sounds good, I will bust out a change that does it via command-line!

**Comment by toolness** [comment]
@jseppi ok I think this is ready now! Originally I was hoping eslint could take in configuration rules from the OS environment, in which case I was just going to add the rule to `Dockerfile` or `docker-compose.yml`, but apparently it can't, so I opted for doing it via command-line as previously discussed.

**Comment by jseppi** [comment]
👍

**Pull request merged**
