### PR TITLE
Run QUnit tests in phantomjs

### PR DESCRIPTION
**Pull request by toolness**
This should have been really easy but it took me a while because `whitenoise` is confusing.

I copied `runner.js` from [qunit-phantomjs-runner](https://github.com/jonkemp/qunit-phantomjs-runner) because:

1. Finding the file when it's installed via `npm` is actually non-trivial due to #373.
2. It's just one dinky file that doesn't change often.

If we really want, though, I can install it via `npm` and add code to locate the `node_modules` directory it's located in.

### CODE REVIEW

**Comment by toolness** [comment]
Uh, QuantifiedCode says "QuantifiedCode — We cannot find the commit for this pull requests."  I guess because GitHub is being weird right now?

**Comment by jseppi** [comment]
I don't mind having `runner.js` committed, but I think we should include the text of its [LICENSE](https://github.com/jonkemp/qunit-phantomjs-runner/blob/master/LICENSE) and where it came from as a comment at the top of the file.

**Comment by toolness** [comment]
@jseppi good idea--I just added it to the directory so that upgrading will be super easy (just copy two files instead of manually reconstructing the `runner.js` one). Also added a readme in that directory to explain our decision...

**Comment by jseppi** [comment]
👍

**Pull request merged**
