### PR TITLE
add link to /updates/ in footer

### LINKED ISSUE #1251: Link to /updates/ from somewhere
Now that we have a human-friendly `/updates/` section, it'd be nice to make it a bit discoverable. Maybe some text at the page footer?

What if we had a link next to "View our code on GitHub" that said "Read about our recent updates"?

### PR DESCRIPTION
**Pull request by jseppi**
Closes #1251 

Looks like:

screen shot 2017-01-30 at 12 21 13 pm

I also did a little CSS/HTML work:
1. Removed the `.github` class
1. Added `.footer_extra` class and div to wrap the github, updates, and icon credits content. I added the `margin-top` that was on `.github` to this new div.
1. Used the `.small` class on the github and updates `<p>`s.
1. Removed commented-out `.email_us` class.

### CODE REVIEW

**Comment by jseppi** [comment]
cc @ericronne

**Comment by ericronne** [comment]
I'd like to make this a little more compact, but i'll do another issue so we can merge this.

**Comment by ericronne** [comment]
@jseppi this merge-able, you think?

**Comment by jseppi** [comment]
Waiting on review from @hbillings

**Comment by jseppi** [comment]
plz review, @hbillings

**Comment by ericronne** [comment]
Since we added icon credits to About (in #1276), we can delete them here, right?

**Comment by jseppi** [comment]
yeah, just fixed the merge conflict, so they're gone now.

**Pull request merged**
