### PR TITLE
Build production scripts before deploy

### PR DESCRIPTION
**Pull request by jseppi**
This PR `unset`s the `DEBUG` env var and runs another gulp build (which will be in "production-mode") before deployments.

To Dos:
- [x] ensure it works (React is in production mode when deployed)
- [x] change back calc-dev deploy to trigger on `develop` branch changes

### CODE REVIEW

**Comment by toolness** [comment]
Wait, we shouldn't actually need to set `NODE_ENV` explicitly ourselves though, should we?  In #725 we made it so that the `DEBUG` setting effectively translates to a `NODE_ENV` setting in the gulpfile, so as long as `DEBUG` is false (i.e. undefined) in production, our `NODE_ENV` should already be set to production...

**Comment by jseppi** [comment]
Right, but we have `DEBUG=yup` on this line of our `.travis.yml`: https://github.com/18F/calc/blob/72103af732a5394428ce1f67d0b56ad015f5c6da/.travis.yml#L39 so the assets are all built in debug mode for testing.

**Comment by toolness** [comment]
OH BLERGHhhhhhhapreogkpoakgr

there's no way to un-`DEBUG=yup`ify the environment for the production use case?

**Comment by jseppi** [comment]
Hrm, I think I could add `unset DEBUG` to the `before_deploy:` section.

**Comment by toolness** [comment]
Yeah that would be supercool!!!!!!!!!!

**Comment by jseppi** [comment]
Alright, how's this, @toolness?

**Comment by jseppi** [comment]
stand by -- testing `unset` works

**Comment by jseppi** [comment]
woot, it works!

screen shot 2017-01-17 at 12 29 06 pm

**Pull request merged**
