### PR TITLE
[WIP] Better page transitions from ajaxforms

### PR DESCRIPTION
**Pull request by toolness**
This adds some optional transitioning in the way ajaxforms redirect users to new pages by supporting the concept of a "visual anchor".  Basically, if an ajaxform specifies an `id` for a visual anchor element, then the ajaxform will smoothly scroll to the visual anchor before redirecting the user's browser.  Once redirected, the loaded page will check to see if it's coming out of a transition and, if so, automatically scrolls the page to the visual anchor.

ajaxform-transition

## Limitations

As can be seen from the above animated GIF, there is an unfortunate side effect of a "flicker" that occurs while the new page is loading. Unfortunately, I don't know of a way to get rid of this without progressively enhancing the entire workflow into a single-page app, which is a fairly big lift.

However, the implementation also adds a `html.ajax-form-transitioning` class at the  beginning of the redirected page load, which gives us room to add other transitional effects, such as the color transitioning of the newly-completed step in the steps widget.

Also, this transition effect only works with ajaxforms, which means that it currently could only work with the steps that involve upload widgets.  In order to make this transition happen across all steps of a workflow, we'd need to convert every step to use an ajaxform, which means tackling issues like #570.

## To do

- [ ] Add documentation.
- [ ] Add tests.
- [ ] Consider making the amount of time spent transitioning (currently 250ms) into a SASS variable.  It'd be nice if the JS knew the value of this but we might have to just duplicate it for now and add a comment reminding devs to keep it in-sync with the SASS variable.

### CODE REVIEW

**Comment by toolness** [comment]
Just added a quick fade so that there's no flicker when the page transition happens:

> ajaxform-transition-with-fade

**Comment by hbillings** [comment]
I'm conflicted about this. I really like the fade-in for the step, but if we feel like we need to automatically scroll the page, that might be an indication that the visual design isn't working. If there's too much fluff at the top of the page, we should rework that information hierarchy so that it's more streamlined. (I totally didn't catch yesterday that you were doing anything other than the color transition or I would have spoken up sooner -- my bad!!)

*takes off information designer hat*

@jseppi and @tram, whatcha think? @toolness, what else are you hoping to use this for?

**Comment by toolness** [comment]
I think you're right @hbillings!  We should definitely think about refactoring the IA... But, I also think that the auto-scroll might still be appropriate for really small screens?  Hmm.

I actually decided to remove the "scroll up to the top of the form before fading out" behavior--before I added the fade-out, I think it was useful because the next page started at the same place. But then we had the flicker, which is why I added the fade-out... But then I think the scroll *with* the fade-out might've been a bit too much, and possibly even disorienting to the user.  So now the form just fades-out and fades-in with the top of the screen anchored to the visual anchor thingy.  And then the current step fades in.

**Comment by toolness** [comment]
Ok, Imma close this one in favor of changing the IA of the site and some other stuff.  We can bring it back later if we want!

**Pull request closed without merging**
