### PR TITLE
Multiple CI deployments

### PR DESCRIPTION
**Pull request by jseppi**
This PR adds support for both staging and production deployments from Travis.

**Staging** - Staging deploys will be triggered on any push to the `master` branch. 
**Production** - Production deploys will be triggered on a tag push to the `master` branch iff it is tagged and the tag looks like a semver version, e.g. `v1.2.3`, as we plan to do according to our RELEASE.md procedure.

Our deployment script (`deploy-travis.sh`) has been updated to accommodate these additional deployment targets. Basically it just checks the `DEPLOY_ENV` environment variable and, based on its value, sets up some more environment-specific variables before calling `cf login` and `cf zero-downtime-push`.

To Do:
- [x] set dev deploy `branch:` back to `develop`
- [x] staging deploy
  - [x] travis deploy trigger
  - [x] make deployer account and save credentials as travis secrets
- [x] prod deploy
  - [x] travis deploy trigger
  - [x] make deployer account and save credentials as travis secrets

Closes https://github.com/18F/calc/issues/1113

### CODE REVIEW

**Comment by jseppi** [comment]
@rogeruiz - I'd appreciate if you could review this strategy and code as well :)

**Comment by jseppi** [comment]
Travis/deploying/secret vars always make so nervous!

**Comment by toolness** [comment]
Yeah, me too 😟

**Comment by toolness** [comment]
Secret vars on travis are especially frustrating because of the bizarre string escaping involved.

**Comment by jseppi** [comment]
Fortunately, the cloud.gov folks stopped providing deployer passwords with characters that would break bash!

**Comment by LinuxBozo** [comment]
LGTM. Great use of branches and tags and `on:` to target specific deployments.

**Pull request merged**
