### PR TITLE
proposed price input

### PR DESCRIPTION
**Pull request by xtine**
Adding Proposed Price input and price callout.

### CODE REVIEW

**Comment by theresaanna** [comment]
Looks good from my side. @maya do you want to take a look?

**Comment by maya** [comment]
Looking good @xtine! Is it possible to display the callout when a user hits "enter" too?

One minor thing, can we drop the proposed price callout to its own line when the viewport gets small enough that it gets covered by the others?

**Comment by maya** [comment]
Here is a screenshot so others can see:

screen shot 2015-06-19 at 5 00 30 pm

**Comment by xtine** [comment]
@maya got the enter submission and media query working

**Comment by maya** [comment]
:+1: this looks good to me @xtine!

**Pull request merged**
