### PR TITLE
PL table changes

### LINKED ISSUE #2098: Implement revised PL analysis intro content for first page and analysis page
## Analyze a proposed price list
Now you can upload a **proposed** service contract and CALC will tell you how its rates compare with prices in our database of approved contracts.

## Price list analysis
Here's how the rates in your proposed contract compare with CALC data. _(upated)_

### PR DESCRIPTION
**Pull request by ericronne**
Primarily table-formatting changes here, but will also closes #2098 (intro text adds)

### CODE REVIEW

**Comment by ericronne** [comment]
Shooting for this design, which requires a new `umbrella-header` class.

Need 👉-ers …
image

@hbillings 
cc: @tram

**Comment by ericronne** [comment]
Don't forget accessibility!
https://www.w3.org/WAI/tutorials/tables/multi-level/

**Comment by tram** [comment]
:chef-kissing-fingers:

**Comment by hbillings** [comment]
Still WIP, or ready to merge into `2077`?

**Comment by ericronne** [comment]
definitely still wip.
i need help.
"👉-ers"

**Pull request merged**
