### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wslack**
updated README that CALC is in beta

### CODE REVIEW

**Comment by theresaanna** [comment]
Good call! This should definitely change. I'm not sure that we're in beta, though, so I talked to @brethauer and it seems like it'd make the most sense if we changed that line to "The tool is live at https://calc.gsa.gov."

If you'd like to make the change, go for it and I'll merge this. Otherwise, we can close this and I'll make the change. You have until Monday. :)

**Comment by wslack** [comment]
Done! this is ready to merge @theresaanna

**Comment by wslack** [comment]
Also the dashboard says Beta :)

**Comment by theresaanna** [comment]
Oh, huh, I've never seen that. @brethauer, what do you think?

Thanks, Will!

**Comment by brethauer** [comment]
Yep I think we should also update the dashboard w/ "live" status  @wslack @theresaanna

**Pull request merged**
