### PR TITLE
Add contract number and vendor UI

### PR DESCRIPTION
**Pull request by hbillings**
While we're waiting on the search returns to be available, I'm rejiggering the schedule selector to be able to accommodate that information when it becomes available.

Done looks like:
~- [ ] Vendor and contract each have a Redux store~ We don't need to capture these currently; just keep track of which one we're showing, which we're now doing with a single new `searchType` store.
~- [ ] The `SearchCategory` component does some logic to first determine if vendor and contract are empty, and, if no `selectedSchedule` exists, defaults to `search in all schedules` if so.~ Also obviated by having a single `searchType` store.
~- [ ] The `SearchCategory` component sets `selectedSchedule` to empty when vendor or contract is chosen.~ No longer necessary, as the `selectedSchedule` check now only happens if `searchType` is `schedule`.
- [x] The search UI's markup can accommodate vendor and contract labels as well as schedule.
- [x] The search UI is accessible.
- [x] Vendor and contract have tests written for them.

### CODE REVIEW

**Comment by hbillings** [comment]
@ericronne, this is ready for your stylistic massaging.

Question about the display text. It stands to reason that when vendor or contract is chosen, the button (collapsed) displays like this:
screen shot 2018-09-12 at 9 12 16 pm

But this means that when it's open, it displays like this (plz to ignore the errant checkmark; that will get fixed next):
screen shot 2018-09-12 at 9 11 31 pm

How should I address this? I think we probably want both the currently selected text and the `Search labor categories` headings to display, but I'm not sure how that should look.

**Comment by ericronne** [comment]
closes #2084

**Comment by ericronne** [comment]
Ah! I could've more explicitly detailed the styling. The text of the selected option should be `$color-base`, and it should get a checkmark. Eg …

image

**Comment by ericronne** [comment]
Ok i'm grokking your point. Since a user who sees a label other than the default will have already used the selector, i doubt there would be a usability hit if we kept the label as you have it, but here's a solution that might be a bit more clear and (dare i say?) eleganté …

image

**Comment by ericronne** [comment]
The gray prompt text should also update to reflect the option which has been chosen …

image

**Comment by ericronne** [comment]
Imma split a branch and take a crack at some of these changes! 🤞 🙏

**Pull request merged**
