### PR TITLE
Upgrade `dj-email-url` for easy TLS email connections

### PR DESCRIPTION
**Pull request by jseppi**
`dj-email-url` v0.1.0 [(changelog)](https://github.com/migonzalvar/dj-email-url#010---2018-03-24) automatically sets `EMAIL_USE_TLS` setting when using the `submission:` "protocol" in the email connection string. This setting is required for `STARTTLS`, which is what we need for use with Amazon SES.

### CODE REVIEW

**Comment by toolness** [comment]
wait, don’t we use https://github.com/migonzalvar/dj-email-url ?  i think we can specify thst config param in the url?

**Comment by jseppi** [comment]
ah, good catch. Didn't think to look there. Apparently we can use `submission:` instead of `smtp:` in the config url: https://github.com/migonzalvar/dj-email-url#smtp-backend

**Comment by jseppi** [comment]
hrm, just tried and it didn't work without the `EMAIL_USE_TLS` explicitly set in `settings.py`...

**Comment by jseppi** [comment]
Oh! Looks like that feature was just added in the version of dj-djang-url released 4 days ago: https://github.com/migonzalvar/dj-email-url/releases

**Comment by jseppi** [comment]
There you go, @toolness!

Note that the `EMAIL_URL` setting will need to start with `submission:` instead of `smtp:`, e.g.:

```sh
EMAIL_URL=submission://<AWS_ID_KEY>:<AWS_SECRET_KEY>@email-smtp.us-east-1.amazonaws.com
```

**Pull request merged**
