### PR TITLE
Tag and release  v2.7.0

### PR DESCRIPTION
**Pull request by jseppi**
### Changed

- Upgraded Django to 1.9.3 (#1526).
- Upgraded jQuery to 3.2.1 (#1539).
- CALC is now prepared for migration to Django 1.10 (#1544). However,
  as the development team currently has a limited amount of time to
  work on CALC, we've decided not to actually migrate to the new
  version of Django, as we may not have time to address any problems
  occurring from the upgrade in the near future.

### Added

- Added support for recording and replaying attempted price list
  submissions (#1491), and added a new **Technical Support Specialist**
  role. This will allow the development team to better serve
  users who are having problems submitting their price lists.
- Added integration with Slack, so that the development team will be
  notified of events happening on CALC and be able to respond quickly
  to anything that needs attention (#1505).
- Added documentation on monitoring CALC (#1518).

### CODE REVIEW

**Comment by jseppi** [comment]
@tram This just needs to be reviewed for change log content, which has been pasted into the root comment of this PR.

**Comment by jseppi** [comment]
Blocked: need to also merge in fix to #1546 before this is released.

**Comment by jseppi** [comment]
Ok, @toolness, I've merged in `develop` with the `update_search_field` fixes, so this is ready to be reviewed again.

**Comment by toolness** [comment]
Should we mention the slackbot stuff?  Even though it's not actually enabled on production, I think it's worth mentioning.

Ditto with the replay functionality--I guess we might need ATO approval before creating any "technical support specialist" users, it's good for folks to know that we've added infrastructure to make it easier to provide technical support to our users.

Documenting that we've prepared CALC for migration to Django 1.10 might also be useful, in case a team other than us ends up inheriting this project!

**Comment by jseppi** [comment]
Yeah! Want to go ahead and add those items to the change log in this branch?

**Comment by toolness** [comment]
Sure, will do!

**Comment by jseppi** [comment]
Also I think we are clear in adding the Tech Support Specialists. That role has been added to our ATO documentation and infra didn't think it would be a problem.

**Comment by jseppi** [comment]
Nice, your changes look 👍

**Comment by toolness** [comment]
Ok, I just added to the changelog and updated this PR's description with the new content!

**Comment by jseppi** [comment]
Ugh, got distracted and forgot to do the rest of release process (bumping version and change log). Incoming.

**Pull request merged**
