### PR TITLE
More-complementary monospace font

### PR DESCRIPTION
**Pull request by ericronne**
Giving this monospace type stack a test drive:
`'Roboto Mono', 'Liberation Mono', 'Source Code Pro', Courier, monospace`

### CODE REVIEW

**Comment by ericronne** [comment]
Roboto Mono and Liberation Mono are front runners. Liberation's letter forms are closer to Libre Franklin than are those of Roboto Mono, but Roboto feels better in terms of weight and size.

Will stew on this over the weekend!

mono-stack

**Comment by hbillings** [comment]
Are these good to go? If so, can we add the `@font-face` rules necessary?

**Comment by ericronne** [comment]
Didn't include a `@font-face` rule. Added font link. That cover it?

**Comment by ericronne** [comment]
_How might we test?_

**Comment by hbillings** [comment]
yay! Um, in the Network tab of the chrome developer tools, you should see a request to Google Fonts for Roboto. I can help!

**Pull request merged**
