### PR TITLE
Fix price cell error styling, improve minimum price message

### LINKED ISSUE #866: Price cell error styling looks a bit off
I think the .errorlist class is misapplied or something.

screen shot 2016-10-05 at 11 09 43 am

### PR DESCRIPTION
**Pull request by jseppi**
Fixes #866 

screen shot 2016-10-05 at 12 58 30 pm

### CODE REVIEW

**Comment by jseppi** [comment]
blarg, the problem was a missing space after "currency": 
`currency{% if row.price_including_iff.errors %}error{% endif %}`

However, now the stupid `$` is janking things up:
screen shot 2016-10-05 at 12 34 37 pm

**Comment by jseppi** [comment]
halp @hbillings, I don't know how to css :(

**Comment by jseppi** [comment]
Looking a little better (I also made the error message more informative):

screen shot 2016-10-05 at 12 46 11 pm

**Comment by jseppi** [comment]
Ok, now it looks nice.

screen shot 2016-10-05 at 12 58 30 pm

I had to remove the `min-width: 1em` that I added back in https://github.com/18F/calc/pull/660#r77554079. The intent of adding that min-width was to make the table columns distribute themselves more equally, but that was kinda hacky. However I don't know a better way to do it.

**Comment by jseppi** [comment]
Please review, @hbillings, because I know very little about what I am doing with css, especially with regard to tables.

**Comment by hbillings** [comment]
Reviewing! (Gotta say, reading this thread reminded me of me trying to write javascript, so <3)

**Comment by hbillings** [comment]
So I'm not sure why, but the error cell is rendering like this for me:
screen shot 2016-10-05 at 2 38 49 pm

**Comment by jseppi** [comment]
oh nose, it looks like that for me also. what did i do 😭

**Comment by jseppi** [comment]
Never mind also, I was on the wrong branch :doh:

**Comment by hbillings** [comment]
Okay, this looks good! I went ahead and removed the `float: right` on number errors, because they really only make a difference for one-line error messages. 👍

**Pull request merged**
