### PR TITLE
[WIP] Random vendor name generator

### PR DESCRIPTION
**Pull request by hbillings**
Output a variety of random vendor names. Currently not hooked up to anything.
TBH, I wasn't quite sure which direction to take this in.

I think I know how to do something like an autofill that displays a button on the first page of the flow that would generate fake data for the session (by using `localStorage`, maybe?) and apply it on a per-page basis before saving it to the model at the end.

I'm not sure how to implement something like the `manage.py seed` command [floated here](https://trello.com/c/OnU8RGHR/161-as-a-developer-i-want-to-autopopulate-fields-in-the-data-capture-flow-so-that-i-can-save-time-and-generate-fake-data-for-testing). I could probably figure out how to generate a JSON file with dummy data, which might be useful for a fixture? But I'm not entirely sure.

Also, I'm aware that this is very much low priority, and that there are UI tasks that require my attention more immediately. So I'm okay if the answer is "you should stop working on this now." ^_^

### CODE REVIEW

**Comment by toolness** [comment]
YASSS 🎉 💥 💥

**Comment by ericronne** [comment]
Oooh what's this, @hbillings?

**Comment by toolness** [comment]
We gotta prioritize this for the next sprint!

[I made a card.](https://trello.com/c/hG2iLDCY/233-as-a-qa-tester-i-want-to-be-able-to-quickly-pre-fill-the-price-list-upload-form-in-with-hilariously-random-data-to-make-manual-t)

**Comment by toolness** [comment]
Well, I guess since we're not actively developing the Data Capture code right now, it wouldn't be _super_ useful, but you're welcome to work on it just for fun... up to you!

**Pull request closed without merging**
