### PR TITLE
[wip] add collectstatic to travis script

### PR DESCRIPTION
**Pull request by jseppi**
Add `python manage.py collectstatic --noinput` to our Travis script so that we can test that Whitenoise will not fail on stuff like missing files as in #772.

### CODE REVIEW

**Comment by jseppi** [comment]
Well, it is failing now, which is the desired outcome, but turns out it is not failing for the right reason.

**Comment by jseppi** [comment]
Closing because this is not a great way to test what we need to test

**Comment by toolness** [comment]
Eh, actually best practices recommend that `DEBUG` *not* be set to true when running tests.  Folks were actually just talking in #django on Slack about it. 😟 

So this might actually be a good idea in the long-run...

**Comment by jseppi** [comment]
That does sound reasonable, but the way I was doing it here was definitely not the place to do it. Another issue?

**Comment by toolness** [comment]
Sure sounds good!

**Pull request closed without merging**
