### PR TITLE
Add npm-shrinkwrap.json

### LINKED ISSUE #1345: Pin all node dependencies
Given #1343 and other problems like it that I've run into in the past, I recommend pinning our node dependencies in our `package.json`.  This will improve dev/prod parity, as well as making the development environment more consistent across our own laptops.

I suspect there is a node-based solution similar to the python-focused `requirements.in` recommended by #514.  If we do something like this, we can make regular PRs that just update the minor/patch version numbers of our node dependencies. I think this will make it a lot easier to track down regressions that are due to package upgrades.

Since node's dependency space is hierarchical rather than flat, it might even behoove us to use `npm shrinkwrap` and commit its results to the repository, but I'm not sure. It looks like this [Keeping Your npm Dependencies Immutable](https://ponyfoo.com/articles/immutable-npm-dependencies) blog post outlines some best practices (well, practices that the author thinks are best, at least).

What do you think @jseppi?

### PR DESCRIPTION
**Pull request by toolness**
This is an attempt to fix #1345 by pinning all node dependencies via [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap).

@jseppi is this all we need to do?

### CODE REVIEW

**Comment by jseppi** [comment]
Might want to add a doc note somewhere. Here's something I wrote in a previous project:

> Note that this application uses a npm-shrinkwrap.json file to freeze npm dependencies. If you'd like to update packages, you will have to do so manually and then re-run npm shrinkwrap.

**Comment by toolness** [comment]
Hmm, I'm not sure if there's currently a good place to put that in the docs... And if I add it somewhere, I'm not very confident it'd be read when someone adds a dependency... Hmm.

What do you think of adding [`npm-shrinkwrap-check`](https://www.npmjs.com/package/npm-shrinkwrap-check) and making it something that `ultratest` and travis both run?  That way if someone forgets to re-run (or didn't know they were supposed to run) `npm shrinkwrap` they will be notified by the test suite.

**Comment by jseppi** [comment]
I'm cool with that!

**Comment by toolness** [comment]
Uhhh, running `npm-shrinkwrap-check -3` gives me:

```
package.json and npm-shrinkwrap.json out of sync
 * a found in package.json but not in npm-shrinkwrap.json
 * b found in package.json but not in npm-shrinkwrap.json
 * evil-transform found in package.json but not in npm-shrinkwrap.json
```

That is very odd because `a`, `b`, and `evil-transform` are nowhere to be found in our `package.json`.

Blegh.

**Comment by jseppi** [comment]
wat

**Comment by jseppi** [comment]
Maybe now we have a good place to put a note about npm-shrinkwrap as of https://github.com/18F/calc/pull/1442!

**Comment by jseppi** [comment]
Or we can rejigger the whole thing to use `yarn` instead, as suggested in #1427

**Comment by toolness** [comment]
Oh lol, I just noticed the top of [`npm-shrinkwrap-check`'s README says](https://github.com/redbooth/npm-shrinkwrap-check#readme):

> This module is deprecated. If you want to painlessly lock your dependencies and
check they are in sync you should use [yarn](https://github.com/yarnpkg/yarn)
and pretend `npm shrinkwrap` ( and this module ) never existed.

So yeah, I guess we should just switch to yarn. Closing this in favor of #1427.

**Pull request closed without merging**
