### PR TITLE
modify Step 1 intro text

### LINKED ISSUE #784: Consider adding text that data capture is for FINAL price list upload
I've noticed in several of the interviews, subjects seem to want to upload non-finalized price lists.

### PR DESCRIPTION
**Pull request by jseppi**
Somewhat minor modifications to the introductory text in Step 1. My aim was to make sure that the user knows we are looking for a finalized price list (ref #784).

I also noticed that the sequence of events mentioned in the "Once you upload a file..." sentence was a bit incorrect/out-of-date, so I took a stab at amending it also.

screen shot 2016-10-03 at 11 52 56 am

I think the spacing looks a bit too big. @hbillings, thoughts?

Closes #784

### CODE REVIEW

**Comment by hbillings** [comment]
yassss 👍 

I agree the spacing is large. I'm noticing that with forms, too, and I'll address it in my current PR.

**Comment by toolness** [comment]
Nice!

The one nit I might make is the phrase "sharing them is easy".  I forget where I read it, but I recall reading something advising content writers avoid phrases like "it's easy", "just", and "simply".  This led to a quick [conversation on #g-content](https://gsa-tts.slack.com/archives/g-content/p1475528292000883) and the content team concurred.

I'm not really sure what should be put in place of "sharing them is easy", if anything--that said, it seems like a pretty tiny and self-contained task, so might be worth posting as a quick 10 minute [writing lab task](https://github.com/18F/writing-lab/issues/new)?  Alternatively, that might be overkill, but since this is the first copy the user will see when they try to upload a price list, maybe it's worth the polish...

**Comment by jseppi** [comment]
I agree, @toolness. Perhaps "and sharing them is easy" could be replaced with something more in-line with the actual goal of CALC, like "and this data will help with future proposed price research."

I am 👍 to getting Writing Lab support.

**Comment by hbillings** [comment]
Didn't the writing lab look at this already? Or am I losing it?

Emileigh Barnes (in my critique group) encouraged me to take out "just" in the original, but didn't mention anything about "easy." I have critique again on Thurs and could bring it up.

**Comment by jseppi** [comment]
Yeah, I think you're right @hbillings. The writing lab had no comments during the review that @tram had them do (ref https://github.com/18F/calc/issues/811).

Merge this now with the "sharing them is easy" and open new issue/PR if necessary?

**Comment by toolness** [comment]
Oh, I thought this PR contains new copy though? The writing lab did indeed look at this in https://github.com/18F/writing-lab/issues/199, but I thought this PR contains new copy, and as such might warrant running by the writing lab again.

Oh weird, now that I'm actually looking at the diff, I'm noticing that the "easy" part was in the original version too. My bad!

**Comment by jseppi** [comment]
Yeah, the copy here is a little new, but mostly just reordering. The newest part is the first sentence, which is to close #784. That was an issue I created myself, so I don't want to be too unilateral in these decisions :)

**Comment by toolness** [comment]
Sorry, I think this is good to merge in that case! :shipit:

**Pull request merged**
