### PR TITLE
[DO NOT MERGE] Ultratap

### PR DESCRIPTION
**Pull request by jseppi**
Here's another idea I just had and coded up real quick. I use `tap` formatters for the tests, which is easily parseable in a consistent way. Then depending on the `--verbose` flag, only print errors or print all output.

Run via `python manage.py ultratap [--verbose]`

I couldn't find a tap output for `flake8`, but I didn't look very hard yet.

### CODE REVIEW

**Comment by toolness** [comment]
Cool! Is there a reason the vast majority of these commits are by me, though, and already present in our `develop` branch? :)

**Comment by jseppi** [comment]
Hrm, that's weird. I opened it against my `ultratest` branch instead of against `develop`.

**Comment by jseppi** [comment]
Looks like `py.test` has pep8 and pyflakes plugins, and it also has a tap output formatter (already used in this PR), so we might be able to use `py.test` for all of the python checks.

**Comment by jseppi** [comment]
Closing this now. I did more exploration and couldn't find TAP formatters for flake8 or pep8/pyflakes.

**Pull request closed without merging**
