### PR TITLE
Spruce up Price List Upload success page

### PR DESCRIPTION
**Pull request by jseppi**
Attempt at closing #653

Please review, @hbillings 

screen shot 2016-10-28 at 8 45 14 am

### CODE REVIEW

**Comment by hbillings** [comment]
Nice! What do you think about breaking the links out as buttons below the alert, so they match the pattern used in the previous screens?

**Comment by jseppi** [comment]
Can do!

**Comment by jseppi** [comment]
@hbillings, like this:

screen shot 2016-10-28 at 8 45 14 am

or like this:

screen shot 2016-10-28 at 8 42 48 am

?

**Comment by jseppi** [comment]
I committed my first option. Easy enough to change though, so just lmk!

**Comment by hbillings** [comment]
The first option looks good to me!

**Pull request merged**
