### PR TITLE
[WIP] Reactify Data Explorer

### PR DESCRIPTION
**Pull request by jseppi**

### CODE REVIEW

**Comment by jseppi** [comment]
So far this is a mess of getting `eslint` and the `airbnb` config working properly. `ultratest`'s `eslint` is ✅, but apparently codeclimate doesn't like some of the new stuff (the dangling commas specifically, which I also don't like). Going to try to figure out wtf those are for.

**Comment by jseppi** [comment]
Airbnb's reasoning for the dangling commas are for cleaner diffs: https://github.com/airbnb/javascript#commas--dangling. I don't like them and they are causing problems in `gulpfile.js` and in codeclimate. Bascially you can only use them in an environment that supports ES2017 or that has gone through a pre-piler.

**Comment by jseppi** [comment]
woot, codeclimate is happy again.

**Comment by toolness** [comment]
@jseppi should this be closed since you decided that it'd be super hard to reactify?  or at least, even if we do reactify it, the data explorer code has changed a lot since #1053 and #1067 ...

**Comment by jseppi** [comment]
Yeah, closing!

**Pull request closed without merging**
