### PR TITLE
Fix remaining visual merge bugs 

### LINKED ISSUE #546: "Go" button appears below "Proposed price" field instead of inline
It should look like this:

> screen shot 2016-08-11 at 6 53 49 pm

But it currently looks like this:

> screen shot 2016-08-11 at 6 53 28 pm

### PR DESCRIPTION
**Pull request by hbillings**
screen shot 2016-08-15 at 3 55 26 pm
screen shot 2016-08-15 at 3 55 21 pm

Related to trello card https://trello.com/c/3IO3aqAQ/121-visual-merge-issues
Closes #546, #547, and the remaining #521 education issue.

### CODE REVIEW

**Comment by jseppi** [comment]
Wooo, nice!

**Comment by jseppi** [comment]
One minor thing I noticed is that the whitespace between the top of the page and the table of results has gotten a bit larger than it is in CALC Prod.

New:
screen shot 2016-08-15 at 4 06 12 pm

Current Prod CALC:
screen shot 2016-08-15 at 4 06 19 pm

**Comment by hbillings** [comment]
@jseppi good eye! Turns out this was caused by margin on the sidebar (weird). Looks like this now:
screen shot 2016-08-15 at 5 08 21 pm

**Comment by jseppi** [comment]
Looks great! Merge away!

**Comment by toolness** [comment]
Yay, merging now! 🎉 🎉 🎉

**Pull request merged**
