### PR TITLE
2075 PL analysis design

### LINKED ISSUE #2075: Design the price list analysis experience
We already have a PR (#997) for a new feature enabling users to analyze a price list, to estimate the relative reasonableness of the rates on that list. We still need to flesh out some design implications for it, though, including (but not limited to) …
- [x] Rename two site tabs (this will make space for the new tab) :
      - "Analyze prices"
      - "Admin"
- [x] Remove the SIN column from step 3
- [x] Update remaining table headers to match verbiage found in data uploader
- [ ] Add detail phrases a la proposed price feature concept (#2030)
- [x] Fix button styles (see uploader for style)
   - [x] "Cancel upload" on step 2
   - [x] Step 3 buttons
- [x] Use narrower card style for steps 1 and 2 (see uploader)
- [x] Apply new step indicator format (enhancement)

### PR DESCRIPTION
**Pull request by ericronne**
Styling for the price list analysis experience.

Closes #2075

### CODE REVIEW

**Comment by ericronne** [comment]
We definitely still need to address the content; that's a big kettle o' 🐟

Not sure why my circleci test is failing. Way above my pay grade there!

**Comment by tadhg-ohiggins** [comment]
The tests are failing on the absence of a `sin` field, looks like. If we do want to remove it from `data_capture/analysis/core.py` as in this PR, we need to also change the tests.

**Comment by ericronne** [comment]
Makes sense. Might this be something you could debug for me? 😉

**Comment by tadhg-ohiggins** [comment]
Sure, if we're certain we want to remove the `sin` field, I can rework the tests to not expect it.

**Comment by ericronne** [comment]
We do! @KellyBailey feels it isn't useful in this context.

**Comment by ericronne** [comment]
images

**Comment by ericronne** [comment]
Thanks @tadhg-ohiggins!

Sadly it looks like it's throwing a shiny, brand new error on us 😑 
Able to suss that? If so, i think we can merge away.

Content still needs work, but that should probably happen on a new branch. Thx!

**Comment by tadhg-ohiggins** [comment]
It's a Snyk error, but Snyk tells me that it's unable to display the organization when I try to get details. I'm hoping Heather can help me out with getting past that.

**Comment by ericronne** [comment]
yep ugh @hbillings helllp

**Comment by hbillings** [comment]
Looking into the Snyk stuff now!

Also, is this a spike or...? The title of this PR and the details of the body are overly light on details.

**Comment by ericronne** [comment]
There's a bulleted to do list in the issue. That too light??

**Comment by hbillings** [comment]
@ericronne Ha, I saw that right after I posted -- see my comment over there. :)

Also, some description of why we're doing this and where it should get merged to would be helpful.  I don't always trust the `X wants to merge 7000 commits to master from this-branch` stuff to be accurate (mostly because I've accidentally opened PRs against `develop` when they should be against something else more often than I'd care to admit).

**Comment by ericronne** [comment]
The plan is to test, with an eye to releasing it to prod. So "Experiment" should probably be removed from the title of #997.

**Comment by hbillings** [comment]
Okay, I think what's going on is that this PR re-introduces bugs that @tbaxter-18f and I fixed with ESLint and Gulp. I think updating this branch from `develop` should fix Snyk.

**Comment by hbillings** [comment]
@ericronne Right, what I'm saying is that I should be able to read the top comment -- the body of the PR -- and know what's going on with this. It's just an organizational thing.

**Comment by hbillings** [comment]
Oh, oof... I wonder if we even _can_ update this branch from `develop`. erghhrm

**Pull request merged**
