### PR TITLE
Enable pep8 in CodeClimate

### PR DESCRIPTION
**Pull request by jseppi**
I looked into adding `flake8` to Travis, but right now the codebase has a lot of errors so I think it would be burdensome (and probably ignored). Instead, I think we should focus on adhering to pep8 on any new code, and cleaning up existing code as we do any modifications.

This PR adds pep8 checking to CodeClimate.

Ref #321

### CODE REVIEW

**Comment by toolness** [comment]
Nice! I'm not familiar with CodeClimate or its configuration settings, so if this looks good to you, feel free to merge it...

**Comment by jseppi** [comment]
Cool. I'm not that familiar with it either. It has GitHub commit/PR integration I think, so I need to figure out how to enable that still.

**Comment by jseppi** [comment]
Unfortunately you can't change the default branch in CodeClimate once a repo has been added. Instead, the repo has to be removed an re-added. Since we've changed our default branch to `develop`, we will have to do that, but we need a CodeClimate admin to help us out.

**Comment by jseppi** [comment]
The default branch has been updated in CodeClimate, so this is good to go. I never got a response from the email I sent to CodeClimate, so I'm not sure how the change happened. It may have been automatic, or someone there may have manually assisted.

**Pull request merged**
