### PR TITLE
Install node modules in Docker container at /calc/node_modules; Implement airbnb react eslinting.

### LINKED ISSUE #569: Improve docker node_modules
Per article at http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
as discussed/used in Checklistomania: https://github.com/18F/checklistomania/pull/100#issuecomment-240492439

### PR DESCRIPTION
**Pull request by toolness**
This fixes #569.

However, there are currently at least two places where we've disabled the `import/no-unresolved` rule (our gulpfile and ultratest) due to the fact that prior to this, we installed our node modules in an unusual location, and eslint doesn't support that because of https://github.com/benmosher/eslint-plugin-import/issues/142.  When trying to remove these Docker-specific conditionals, eslint still failed--not because it couldn't find our third-party node modules, but because it couldn't find any of our first-party modules with `.jsx` extensions!

awgpanpgiwenigrwhniperpmehti

I fiddled with trying to get eslint to recognize our modules with `.jsx` extensions via `eslint-plugin-import`'s [`import/extensions` setting](https://www.npmjs.com/package/eslint-plugin-import#importextensions) but that didn't seem to fix it.

So this just changes the `Dockerfile`.

### CODE REVIEW

**Comment by toolness** [comment]
Wait... since we apparently need to have `import/no-unresolved` turned off in order for eslint to work *at all*, not just in docker, shouldn't we move that out of the Docker-specific conditionals in the gulpfile/ultratest and into `.eslintrc`?!  Aragiagwiarharhghhhhh

**Comment by jseppi** [comment]
👀

**Comment by jseppi** [comment]
I'm working up another PR based on this one to add react eslinting and fix-up the imports stuff.

**Comment by jseppi** [comment]
dangit, CodeClimate!

**Comment by jseppi** [comment]
@toolness - merge when ready!

**Comment by toolness** [comment]
@jseppi actually can you double-check the merge conflict I just resolved in 4cb2b965a7c6b11d1b509b8c38f2a7a396ec41b6?  If that looks good to you and travis likes it, feel free to merge.

**Comment by jseppi** [comment]
heh, I think CodeClimate stalled because of the GitHub outage, but I can't figure out how to restart it.

**Comment by jseppi** [comment]
@toolness: I pushed another small change (moving py.test to the end of ultratest's tests). Hope that's ok!

**Comment by jseppi** [comment]
wooooot!

**Pull request merged**
