### PR TITLE
Restyle form inputs for step 1 & 2

### LINKED ISSUE #739: Display contract start and end date boxes side by side

### PR DESCRIPTION
**Pull request by hbillings**
Closes #739, #736 

Really, the only difference for step 1 is graying the help text. Here's what step 2 looks like:
screen shot 2016-09-14 at 10 35 53 pm

I ended up just writing the HTML for the radio button form directly in the template. Ugh. I investigated making a custom radio button widget, but TBH after 40 minutes of wrestling with it, I gave up for the more expedient approach. (I'm sure I was making it more difficult than it needed to be!)

### CODE REVIEW

**Comment by toolness** [comment]
Woooo this looks so much better than our current janky radio buttons.

Bummer about the widget though--want me to try making one in a separate PR?

**Comment by hbillings** [comment]
@atul Sure! I just didn't want to hold things up any more than necessary. But I'd be interested in seeing what you write. 😁

**Comment by hbillings** [comment]
Merged @toolness's PR (I got the GH handle right that time, oy, me), and now I'm getting `TypeError: __init__() missing 5 required positional arguments: 'name', 'value', 'attrs', 'choice', and 'index'`. This happens on the styleguide and on step 2. Thoughts?

**Comment by jseppi** [comment]
This looks so much better! 🎉 

I pulled this branch and ran it locally and found a couple things:

* The spacing between the help text and the form field looks a little big to me:
screen shot 2016-09-16 at 11 09 50 am
* I couldn't actually submit the Step 2 form due to an unspecified error. I think it might be because the Contract Year field is missing:
screen shot 2016-09-16 at 11 10 21 am

**Comment by toolness** [comment]
Ok @jseppi, I added #763 to address your concerns while @hbillings is out... Feel free to merge that into this PR if you want, or we can wait for @hbillings to look at it, whatever works!

**Comment by hbillings** [comment]
@jseppi wait, do the contract years not show up at all for you?!?

**Comment by jseppi** [comment]
👍 This looks great!

**Pull request merged**
