### PR TITLE
Improve our button set

### PR DESCRIPTION
**Pull request by ericronne**

### CODE REVIEW

**Comment by ericronne** [comment]
@hbillings we may want to pair to take this to the next level:
- [ ] Add white button (as seen in the footer log-in utility)
- [ ] Format the various button states to show by default (incl focus #1886)

Then i can lay out the examples. thx!

**Comment by ericronne** [comment]
Blocked until @hbillings and i get a chance to pair

**Comment by ericronne** [comment]
All looks brills, except the sizes are still inconsistent for me. Local issue?

image

**Comment by ericronne** [comment]
Wish i could debug this sizing wackery :/

Default size for buttons should be 40px tall, and the outline on the secondary button should be on the inside, rather than the outside.

Thk u!!

**Comment by hbillings** [comment]
@ericronne Are you sure you pulled? I fixed both of those in the PR I just merged in (and this branch now looks fine on my computer).

**Comment by ericronne** [comment]
Docker restart FTW
❤️ @hbillings 

image

**Comment by hbillings** [comment]
dockerrrrrrrrrrrr

**Comment by ericronne** [comment]
Added 6px to height, feeling mergy!

image

**Comment by hbillings** [comment]
Is this ready for review? I see it's not WIP any more, but also that there are unchecked checkmarks in the todos.

**Comment by ericronne** [comment]
#1886 is probably best handled in a new PR

I've done a visual check on the site; you may want to as well, to check that box!

**Pull request merged**
